### PR TITLE
Alternate enum generator

### PR DESCRIPTION
**Pull request by rikrak**
Hi,

I've back-ported an enum generator that I implemented in one of my projects.  It allows generating of enum values with a frequency weighting, or excluding values altogether.  It also demos a fluent specification style.

### CODE REVIEW

**Comment by PrintsCharming** [comment]
Merged into 1_4Pre
Thanks!

**Comment by PrintsCharming** [comment]
This is pretty cool.

**Comment by rikrak** [comment]
Thanks! :-)
I've a few more things to submit, but I won't have chance to work on them for a week or two. Hopefully should have them done by the end of April.
If you're interested I've committed some code to my fork

**Comment by PrintsCharming** [comment]
Hold off on the PRs. I did a massive amount of renaming and code clean up. I'm going to finish this branch up in the next day or two and then you should work off that.

**Pull request closed without merging**
