### PR TITLE
CultureInfo properties generator

### PR DESCRIPTION
**Pull request by ushenkodmitry**
Might be handy in international application development. 
Also i've added .vs folder to the gitignore file.

### CODE REVIEW

**Comment by rikrak** [comment]
@ushenkodmitry Minor review comment:
I think the randomisation in the generate method is permanently excluding the last item in the list.  
The line:
`var next = _random.Next(0, cultures.Length - 1);`
Should be:
`var next = _random.Next(0, cultures.Length);`
(The max value of random is exclusive: https://msdn.microsoft.com/en-us/library/2dx6wyd4(v=vs.110).aspx)

I just fixed this in my own pull requests too!  :-)

**Comment by ushenkodmitry** [comment]
Thanks for the comment. I will update PR.

чт, 22 марта 2018 г., 13:47 Rik Crompton <notifications@github.com>:

**Comment by PrintsCharming** [comment]
Fixed this issue @rikrak mentioned and merged into 1-3Pre

**Comment by ushenkodmitry** [comment]
Thanks!


пт, 23 марта 2018 г., 6:14 Ryan Smith <notifications@github.com>:

**Pull request closed without merging**
